name = 'cloudflare-r2-oss'
main = "src/index.ts"
compatibility_date = "2024-09-25"

[assets]
directory = "./static"
binding = "ASSETS"

[[r2_buckets]]
binding = "BUCKET"
bucket_name = "disk"

[vars]
PUBURL = "https://disk.aneko.ink"
TURNSTILE_SECRET = "0x4AAAAAADVWOePrkWv_vDrrSeo_MG7PiA4"
